name: Trigger auto deployment for auth

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - 'src/Services/Authentication/**'
    - '.github/workflows/auth-AutoDeployTrigger-c0313fe7-a26f-4f78-8f64-0eafb0c17cb5.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AUTH_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}/src/Services/Authentication 
          registryUrl: hrmreg.azurecr.io
          registryUsername: ${{ secrets.AUTH_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.AUTH_REGISTRY_PASSWORD }}
          containerAppName: auth
          resourceGroup: HRM
          imageToBuild: hrmreg.azurecr.io/auth:${{ github.sha }}
          dockerfilePath: Dockerfile

     

